"""Test requirements for division levels."""

from typing import Any

# Test requirements for division levels (26-41, 43-45)
DIVISION_TEST_REQUIREMENTS: dict[int, dict[str, Any]] = {
    26: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_26",
    },
    27: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_27",
    },
    28: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_28",
    },
    29: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_29",
    },
    30: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_30",
    },
    31: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_31",
    },
    32: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_32",
    },
    33: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_33",
    },
    34: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_34",
    },
    35: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_35",
    },
    36: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_36",
    },
    37: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_37",
    },
    38: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_38",
    },
    39: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_39",
    },
    40: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_40",
    },
    41: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_41",
    },
    43: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_43",
    },
    44: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_44",
    },
    45: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_45",
    },
}

