"""Test requirements for multiplication levels."""

from typing import Any

# Test requirements for multiplication levels (9-21, 24, 25, 42)
MULTIPLICATION_TEST_REQUIREMENTS: dict[int, dict[str, Any]] = {
    9: {
        "sessions_required": 3,
        "question_count": 25,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_9",
    },
    10: {
        "sessions_required": 3,
        "question_count": 25,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_10",
    },
    11: {
        "sessions_required": 3,
        "question_count": 25,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_11",
    },
    12: {
        "sessions_required": 3,
        "question_count": 25,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_12",
    },
    13: {
        "sessions_required": 3,
        "question_count": 25,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_13",
    },
    14: {
        "sessions_required": 3,
        "question_count": 25,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_14",
    },
    15: {
        "sessions_required": 3,
        "question_count": 25,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_15",
    },
    16: {
        "sessions_required": 3,
        "question_count": 25,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_16",
    },
    17: {
        "sessions_required": 3,
        "question_count": 25,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_17",
    },
    18: {
        "sessions_required": 3,
        "question_count": 25,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_18",
    },
    19: {
        "sessions_required": 3,
        "question_count": 25,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_19",
    },
    20: {
        "sessions_required": 3,
        "question_count": 25,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_20",
    },
    21: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_21",
    },
    24: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_24",
    },
    25: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_25",
    },
    42: {
        "sessions_required": 3,
        "question_count": 30,
        "passing_score": 0.80,
        "missed_questions_threshold": 3,
        "missed_questions_window_days": 7,
        "test_type": "level_42",
    },
}

